add antidiction practices
taptap/tds-blog pull request #13
Opened 2022-02-15 07:45 UTC by WatchMan-Wang

增加实名认证防沉迷说明

2022-02-15 07:47 UTC, kylinbin commented on _posts/tapsdk-tap-antiaddiction-practice.md
> +按照共和国的新闻出版署[《关于进一步严格管理切实防止未成年人沉迷网络游戏的通知》](https://www.nppa.gov.cn/nppa/contents/279/98792.shtml)，各游戏出版运营企业均须在游戏内落实游戏实名认证和防沉迷新策略。依此 TDS 推出「防沉迷」功能，助力游戏厂商发展。
```suggestion
按照国家新闻出版署[《关于进一步严格管理切实防止未成年人沉迷网络游戏的通知》](https://www.nppa.gov.cn/nppa/contents/279/98792.shtml)，各游戏出版运营企业均须在游戏内落实游戏实名认证和防沉迷新策略。依此 TDS 推出「防沉迷」功能，助力游戏厂商发展。
```

2022-02-15 07:49 UTC, kylinbin commented on _posts/tapsdk-tap-antiaddiction-practice.md
> +在使用 TDS 实名认证和防沉迷服务之前，游戏厂商需要完成一些前期准备工作。详情请参考[「注册中宣部实名认证系统」](https://developer.taptap.com/docs/sdk/anti-addiction/features/#%E6%B3%A8%E5%86%8C%E4%B8%AD%E5%AE%A3%E9%83%A8%E5%AE%9E%E5%90%8D%E8%AE%A4%E8%A
TapDC 后台 -> TapTap 开发者中心后台

2022-02-15 07:50 UTC, kylinbin commented on _posts/tapsdk-tap-antiaddiction-practice.md
> +TapTap 快速认证服务顾名思义，是通过玩家已经在 Tap 社区客户端已经有账号登陆，而且该账号是已经通过 Tap 社区客户端实名过的。**这种方式的前提是游戏需要接入 [TapTap 登录](https://developer.taptap.com/docs/sdk/taptap-login/features/)功能**，游戏可以选择通过基于[内建账户系统](https://develope
TapTap 客户端 -> Tap 社区客户端

2022-02-15 08:11 UTC, WatchMan-Wang commented on _posts/tapsdk-tap-antiaddiction-practice.md
> +TapTap 快速认证服务顾名思义，是通过玩家已经在 Tap 社区客户端已经有账号登陆，而且该账号是已经通过 Tap 社区客户端实名过的。**这种方式的前提是游戏需要接入 [TapTap 登录](https://developer.taptap.com/docs/sdk/taptap-login/features/)功能**，游戏可以选择通过基于[内建账户系统](https://develope
这个暂定 TapTap 客户端吧。想到更好的再近一步优化。

2022-02-15 08:37 UTC, weakish approved these changes
赞！

（里面部分内容也可以加到文档中去，文档现在对 UI 界面的说明和报错等讲得没有这里清楚）

2022-02-15 08:37 UTC, weakish commented on _posts/tapsdk-tap-antiaddiction-practice.md
> +![](/post-images/tap_antidiction_02.jpg)
这里其实没有必要用图片，直接贴文字（代码块）就行

2022-02-15 08:46 UTC, WatchMan-Wang commented on _posts/tapsdk-tap-antiaddiction-practice.md
> +![](/post-images/tap_antidiction_02.jpg)
我当初感觉有图会更醒目，会更引起开发者的重视。
这里代码块不好添加，因为不知道开发者最后如何获取设备唯一标识。

2022-02-15 09:06 UTC, WatchMan-Wang commented on _posts/tapsdk-tap-antiaddiction-practice.md
> +![](/post-images/tap_antidiction_02.jpg)
文档我计划进行优化下，有张图还需要进行替换。

2022-02-16 03:45 UTC, merged

2022-02-16 03:46 UTC, fuchenshi requested changes

2022-02-16 03:46 UTC, fuchenshi commented on _posts/tapsdk-tap-antiaddiction-practice.md
> +在使用 TDS 实名认证和防沉迷服务之前，游戏厂商需要完成一些前期准备工作。详情请参考[「注册中宣部实名认证系统」](https://developer.taptap.com/docs/sdk/anti-addiction/features/#%E6%B3%A8%E5%86%8C%E4%B8%AD%E5%AE%A3%E9%83%A8%E5%AE%9E%E5%90%8D%E8%AE%A4%E8%A
```suggestion
在使用 TDS 实名认证和防沉迷服务之前，游戏厂商需要完成一些前期准备工作。详情请参考[「注册中宣部实名认证系统」](https://developer.taptap.com/docs/sdk/anti-addiction/features/#%E6%B3%A8%E5%86%8C%E4%B8%AD%E5%AE%A3%E9%83%A8%E5%AE%9E%E5%90%8D%E8%AE%A4%E8%AF%81%E7%B3%BB%E7%BB%9F)。**注意：没有版号的游戏想要使用 TDS 的防沉迷功能，需要在 TapTap 开发者中心后台提交工单进行申请，工单分类选择「游戏服务支持 > 防沉迷新政相关」。无版号游戏没有开通实名认证防沉迷服务是无法使用 TDS 的实名认证防沉迷功能的。**
```

2022-02-16 03:46 UTC, fuchenshi commented on _posts/tapsdk-tap-antiaddiction-practice.md
> +            // 这种状态，SDK 内部封装的弹窗会被触发，玩家只能选择「切换账号」(前提是显示切换账号按钮 bool showSwitchAccount = true )或者「退出游戏」
```suggestion
            // 这种状态，SDK 内部封装的弹窗会被触发，玩家只能选择「切换账号」（前提是显示切换账号按钮 bool showSwitchAccount = true）或者「退出游戏」
```

2022-02-16 03:46 UTC, fuchenshi commented on _posts/tapsdk-tap-antiaddiction-practice.md
> +            // 退出账号，当调用 AntiAddictionUIKit.Logout() 接口触发
```suggestion
            // 退出账号，当调用 AntiAddictionUIKit.Logout() 接口时触发
```

2022-02-16 03:46 UTC, fuchenshi commented on _posts/tapsdk-tap-antiaddiction-practice.md
> +TapTap 快速认证服务顾名思义，是通过玩家已经在 Tap 社区客户端已经有账号登陆，而且该账号是已经通过 TapTap 客户端实名过的。**这种方式的前提是游戏需要接入 [TapTap 登录](https://developer.taptap.com/docs/sdk/taptap-login/features/)功能**，游戏可以选择通过基于[内建账户系统](https://develop
```suggestion
TapTap 快速认证服务顾名思义，是通过玩家在 Tap 社区客户端已经拥有的账号登录，而且该账号是已经通过 TapTap 客户端实名过的。**这种方式的前提是游戏需要接入 [TapTap 登录](https://developer.taptap.com/docs/sdk/taptap-login/features/)功能**，游戏可以选择通过基于[内建账户系统](https://developer.taptap.com/docs/sdk/authentication/features/)接入 TapTap 登录，或者以[单纯 TapTap 用户认证](https://developer.taptap.com/docs/sdk/taptap-login/guide/tap-login/)的方式接入 TapTap 登录。登录成功后需要将 TapSDK 返回的玩家属性用户唯一标识作为参数传递给防沉迷的接口，从而才可以开始 TapTap 快速认证。具体的代码示范如下：
```

2022-02-16 03:46 UTC, fuchenshi commented on _posts/tapsdk-tap-antiaddiction-practice.md
> +正确调用上述接口移动端打包后可以看到如下的弹窗
```suggestion
正确调用上述接口移动端打包后可以看到如下的弹窗：
```

2022-02-16 03:46 UTC, fuchenshi commented on _posts/tapsdk-tap-antiaddiction-practice.md
> +无论采用哪种方式进行实名认证，调用的接口中有个参数需要额外注意下，**userIdentifier：玩家的唯一标识**。如果第一次认证后，紧接着进行第二次认证，userIdentifier 值没有改变的话，TapTap 服务端根据该 userIdentifier 上次的认证结果并结合当前时间段并直接进行返回认证结果，省去姓名和身份证号的输入。所以，不同的玩家，这里的唯一标识应该要保持不同。
```suggestion
无论采用哪种方式进行实名认证，调用的接口中有个参数需要额外注意下，**userIdentifier：玩家的唯一标识**。如果第一次认证后，紧接着进行第二次认证，userIdentifier 值没有改变的话，TapTap 服务端会根据该 userIdentifier 上次的认证结果结合当前时间段直接返回认证结果，省去姓名和身份证号的输入。所以，不同的玩家，这里的唯一标识应该要保持不同。
```

2022-02-16 03:46 UTC, fuchenshi commented on _posts/tapsdk-tap-antiaddiction-practice.md
> +有的开发者可能会将该参数赋值为获取到的设备唯一标识，但是真的不太建议这样操作，因为安卓碎片化较为严重、可能玩家并不会同意获取设备信息权限等因素导致获取到的设备唯一标识为空，从而导致 userIdentifier 为空，如果代码不够健壮，非空判定比较少。结果就是无法正常使用实名认证功能。具体的异常可能是：
```suggestion
有的开发者可能会将该参数赋值为获取到的设备唯一标识，但是真的不太建议这样操作，因为安卓碎片化较为严重，玩家不同意获取设备信息权限等因素可能导致获取到的设备唯一标识为空，从而导致 userIdentifier 为空。如果代码不够健壮，非空判定比较少，结果就会是无法正常使用实名认证功能。具体的异常可能是：
```

2022-02-16 03:46 UTC, fuchenshi commented on _posts/tapsdk-tap-antiaddiction-practice.md
> +实名认证后，可以统一调用如下接口获取当前玩家的年龄段
```suggestion
实名认证后，可以统一调用如下接口获取当前玩家的年龄段：
```

2022-02-16 03:46 UTC, fuchenshi commented on _posts/tapsdk-tap-antiaddiction-practice.md
> +仅允许未成年人在周五、周六、周日和法定节假日的 20:00 至 21:00 进行游戏。非允许游戏时间段内，SDK 封装了相应的逻辑会被触发，弹窗提示框提醒未成年无法继续游戏。此时的未成年玩家最多有两种选择：「退出游戏」或者「切换账号」。
```suggestion
仅允许未成年人在周五、周六、周日和法定节假日的 20:00 至 21:00 进行游戏。非允许游戏时间段内，SDK 封装的相应逻辑会被触发，弹出提示框提醒未成年无法继续游戏。此时的未成年玩家最多有两种选择：「退出游戏」或者「切换账号」。
```

2022-02-16 03:46 UTC, fuchenshi commented on _posts/tapsdk-tap-antiaddiction-practice.md
> +如果初始化 SDK 时设置的一个参数 showSwitchAccount 为 false 表示不显示「切换账号」按钮，那此时的未成年玩家只能选择「退出游戏」了。
```suggestion
如果初始化 SDK 时设置的一个参数 showSwitchAccount 为 false（表示不显示「切换账号」按钮），那此时的未成年玩家只能选择「退出游戏」了。
```

2022-02-16 06:22 UTC, WatchMan-Wang commented on _posts/tapsdk-tap-antiaddiction-practice.md
> +如果初始化 SDK 时设置的一个参数 showSwitchAccount 为 false 表示不显示「切换账号」按钮，那此时的未成年玩家只能选择「退出游戏」了。
https://github.com/taptap/tds-blog/pull/14 已经解决

2022-02-16 06:22 UTC, WatchMan-Wang commented on _posts/tapsdk-tap-antiaddiction-practice.md
> +仅允许未成年人在周五、周六、周日和法定节假日的 20:00 至 21:00 进行游戏。非允许游戏时间段内，SDK 封装了相应的逻辑会被触发，弹窗提示框提醒未成年无法继续游戏。此时的未成年玩家最多有两种选择：「退出游戏」或者「切换账号」。
https://github.com/taptap/tds-blog/pull/14 已经解决

2022-02-16 06:22 UTC, WatchMan-Wang commented on _posts/tapsdk-tap-antiaddiction-practice.md
> +实名认证后，可以统一调用如下接口获取当前玩家的年龄段
https://github.com/taptap/tds-blog/pull/14 已经解决

2022-02-16 06:22 UTC, WatchMan-Wang commented on _posts/tapsdk-tap-antiaddiction-practice.md
> +有的开发者可能会将该参数赋值为获取到的设备唯一标识，但是真的不太建议这样操作，因为安卓碎片化较为严重、可能玩家并不会同意获取设备信息权限等因素导致获取到的设备唯一标识为空，从而导致 userIdentifier 为空，如果代码不够健壮，非空判定比较少。结果就是无法正常使用实名认证功能。具体的异常可能是：
https://github.com/taptap/tds-blog/pull/14 已经解决

2022-02-16 06:23 UTC, WatchMan-Wang commented on _posts/tapsdk-tap-antiaddiction-practice.md
> +无论采用哪种方式进行实名认证，调用的接口中有个参数需要额外注意下，**userIdentifier：玩家的唯一标识**。如果第一次认证后，紧接着进行第二次认证，userIdentifier 值没有改变的话，TapTap 服务端根据该 userIdentifier 上次的认证结果并结合当前时间段并直接进行返回认证结果，省去姓名和身份证号的输入。所以，不同的玩家，这里的唯一标识应该要保持不同。
https://github.com/taptap/tds-blog/pull/14 已经解决

2022-02-16 06:23 UTC, WatchMan-Wang commented on _posts/tapsdk-tap-antiaddiction-practice.md
> +正确调用上述接口移动端打包后可以看到如下的弹窗
https://github.com/taptap/tds-blog/pull/14 已经解决

2022-02-16 06:23 UTC, WatchMan-Wang commented on _posts/tapsdk-tap-antiaddiction-practice.md
> +TapTap 快速认证服务顾名思义，是通过玩家已经在 Tap 社区客户端已经有账号登陆，而且该账号是已经通过 TapTap 客户端实名过的。**这种方式的前提是游戏需要接入 [TapTap 登录](https://developer.taptap.com/docs/sdk/taptap-login/features/)功能**，游戏可以选择通过基于[内建账户系统](https://develop
https://github.com/taptap/tds-blog/pull/14 已经解决

2022-02-16 06:23 UTC, WatchMan-Wang commented on _posts/tapsdk-tap-antiaddiction-practice.md
> +            // 退出账号，当调用 AntiAddictionUIKit.Logout() 接口触发
https://github.com/taptap/tds-blog/pull/14 已经解决

2022-02-16 06:23 UTC, WatchMan-Wang commented on _posts/tapsdk-tap-antiaddiction-practice.md
> +            // 这种状态，SDK 内部封装的弹窗会被触发，玩家只能选择「切换账号」(前提是显示切换账号按钮 bool showSwitchAccount = true )或者「退出游戏」
https://github.com/taptap/tds-blog/pull/14 已经解决

2022-02-16 06:23 UTC, WatchMan-Wang commented on _posts/tapsdk-tap-antiaddiction-practice.md
> +在使用 TDS 实名认证和防沉迷服务之前，游戏厂商需要完成一些前期准备工作。详情请参考[「注册中宣部实名认证系统」](https://developer.taptap.com/docs/sdk/anti-addiction/features/#%E6%B3%A8%E5%86%8C%E4%B8%AD%E5%AE%A3%E9%83%A8%E5%AE%9E%E5%90%8D%E8%AE%A4%E8%A
https://github.com/taptap/tds-blog/pull/14 已经解决