refactor: use pre/post hook to move image dir
taptap/tds-blog pull request #26
Opened 2022-03-11 13:16 UTC by weakish

symlink seems not work with @netlify/plugin-nextjs

see also #19 #23 #25

2022-03-12 06:39 UTC, fuchenshi requested changes

2022-03-12 06:39 UTC, fuchenshi commented on package.json
> +    "prebuild": "rm -rf public/post-image && cp -r post-images public/post-images",
如果是在本地开发（`next dev`）过程中想要添加图片，是应该分别往 `post-images` 和 `public/post-images` 里面添加一遍么？感觉这样设计容易导致开发人员困惑或是犯错（往 `post-images` 添加后发现本地预览没有出现图片，或者往 `public/post-images` 里面添加后忘记往 `post-images` 添加，下次启动本地开发时意外删除之前添加的图片）。

另外 `rm -rf public/post-image` 应为 `rm -rf public/post-images`。

2022-03-14 04:10 UTC, weakish commented on package.json
> +    "prebuild": "rm -rf public/post-image && cp -r post-images public/post-images",
路径错误在 [032e29a](https://github.com/taptap/tds-blog/pull/26/commits/032e29ae242698c6731980fecccd1dd582cbca7c) 中修正了。

如果 `next dev` 期间想添加图片，可以先停止 `next dev`，往 post-images 里添加后在重新跑 `next dev`，或者就像你说的那样往两个目录中都添加一份。

2022-03-14 05:18 UTC, fuchenshi approved these changes

2022-03-14 05:18 UTC, merged